### ISSUE TITLE
없는 사용자/질문 예외처리

### ISSUE THREAD

**Issue by Raoun4136** [telling-me/tellingme-client#34]
### Description

개발 QA전 undefined 사용자 및 질문을 Redirect 시키도록 예외처리 필요

### ✔ TODO

- [x] 질문 없을 때 처리
- [x] 사용자 없을 때 처리 
- [x] 이모티콘 없을 때 처리

### 🔴 ETC

기타 사항을 적어주세요.
예상 개발 기간 : 1일
