### ISSUE TITLE
SEO 적용

### ISSUE THREAD

**Issue by Raoun4136** [telling-me/tellingme-client#36]
### Description

SEO 적용 및 Open Graph 적용 이슈

### ✔ TODO

- [x] SEO 태그 입력
- [ ] google search console 추가
- [ ] naver search advisor 추가
- [x] Open Graph

### 🔴 ETC

기타 사항을 적어주세요.
예상 개발 기간 : 3일
