### ISSUE TITLE
개발 QA - 박성오

### ISSUE THREAD

**Issue by Raoun4136** [telling-me/tellingme-client#47]
### Description

2023.06.06(수)에 확인된 개발 QA 작업 (박성오) 입니다.

---
`추가` 2023.06.14(수)에 확인된 개발 내부 QA 작업 (박성오) 입니다.

### ✔ TODO

랜딩페이지
- [x] 네비게이션 바 고정
- [x] 네비게이션 바 배경색 맨 위에서는 투명 → 내리면 색 생김
- [x] 보일때 투명도 조절 애니메이션
- [x] 타이틀 문구 간격 10px (태블릿, pc버전) (모바일은 8px 그대로)
- [x] 6:00 AM 밑 조약돌 앞으로
- [x] 시간 올라가는 애니메이션 추가
- [x] 새로운 듀이 다시 전달해서 교체하기
- [x] 답변 슬라이드 - 카드 3개가 온전히 보이게 수정
- [x] 답변 슬라이드 - 왼쪽 사이드에서 카드가 씹히는 경우가 없도록 만들기
    - [x] [선택 1] 애니메이션으로 고정 + 점 추가
    - [ ] [선택 2] 양방향 버튼으로 사용자가 움직일 수 있다는 인식을
- [x] ‘나를 위한 시간~’ 간격 10px으로 수정
- [x] 뉴스레터 신청 / 로그인하기 버튼 폰트 크기 수정
- [x] 미디엄 로고 추가하기
- [x] ‘시작하기’로 통일 (로그인하기 X)
- [x] ‘뉴스레터 신청’ > '텔링미 소식 구독' 버튼으로 수정
- [ ] 플로팅 버튼 추가

홈 탭
- [x] 둥둥 아이콘 그림자 넣기
- [x] 질문, 아래문구 줄간격 수정
- [x] 감정 선택할 때 그 감정에 해당하는 텍스트(’행복해요’) 나오게
- [x] 감정 선택할 때 선택된 듀이 빼고는 투명도 조절
- [x] 펜 아이콘 호버 추가
- [x] 배경 원 다시 그리기
- [ ] 프리미엄 감정들은 자물쇠로 잠구기, 누르면 프리미엄 모드 구매해야 사용할 수 있다는 메시지
- [x] 왼쪽 위 tellingme 아이콘 눌렀을 때
    - [x] 랜딩페이지 - 새로고침
    - [x] 로그인 후 - 홈 탭

질문, 답변 기록 화면
- [x] 질문, 아래문구 줄간격 수정
- [x] 답변 입력창 500>300자로 수정 (프리미엄이 500, 기본은 300자)
- [x] 완료 버튼 옮기기
- [x] 접기 버튼 추가

공사 화면
- [x] 소통공간 - 막혀있는 버튼 활성화하고 누르면 공사중이라고 뜨도록
- [x] 답변 화면 슬라이드형

ALL
- [x] 403,500,404에러 페이지 redirect
- [x] 민지 로딩컴포넌트 개발완료 시 로딩 붙이기

meta태그
- [x] description 수정
- [x] robots.txt 확인
- [x] 서버 co.kr 연결 문제 확인
- [x] 모든 기종 favicon, og:image 확인

---
`추가`
랜딩페이지
- [x] 캐릭터 변경
- [x] 듀이티콘 정정
- [x] 노션 링크 연결
- [ ] 스크롤 중복
- [ ] 아이폰 레이어 뒤로 스크롤이 숨음
- [ ] pc에서 네비게이션바 레이아웃에 맞지 않음

APP
- [x] 배경화면 UI
- [x] 점선 수정
- [x] 하루 초록색 변경
- [x] 네비게이션 바 투명
- [x] 질문 볼드체 변경
- [x] 윙펜 아이콘 - 답변 완료 사이 패딩 수정
- [x] 감정 모달 취소/확인 버튼 색 변경
- [x] 공백 제외 -> 공백 포함으로 변경
- [ ] 웹 이모지 7byte 확인
- [x] 탭 바 왼쪽 오른쪽 변경
- [x] 날짜 오류

오류 페이지
- [x] 다이얼로그, 태블릿 pc크기 변경

### 🔴 ETC

기타 사항을 적어주세요.
예상 개발 기간 : 4일 + 7일
