### ISSUE TITLE
개발 QA - 김민지

### ISSUE THREAD

**Issue by wisdomin121** [telling-me/tellingme-client#48]
### Description

2023.06..06(수)에 확인된 개발 QA 작업 (김민지) 입니다.

### ✔ TODO

로그인과 회원가입은 feat/#2/kakao_login 브랜치에서 작업하였습니다.

세팅 페이지

- [x] 모바일 화면에서 개인정보 수정 페이지 헤더만 다름
- [x] 모바일 화면에서 푸시 알림 토글 오류 있음 
- [x] 토큰이 삭제가 안돼요
- [x] 세팅 api 주소 변경
- [x] 설정에서 고민이 없는데도 완료가 눌려버림
- [x] 성별, 생년월일 고정된 값은 disabled처리 (색을 바꾸어서) 및 커서 손바닥으로 안바뀌도록
- [x] 기타 - 직접 입력 안 적었을 때
- [x] 고민 '건강' 추가

기타

- [x] 프록시 주소 변경

### 🔴 ETC

기타 사항을 적어주세요.
예상 개발 기간 : 4일
