### ISSUE TITLE
개발 QA - 김민지

### ISSUE THREAD

**Issue by wisdomin121** [telling-me/tellingme-client#56]
### Description

2023.06.14(수)부터 확인된 개발 QA 작업 (김민지) 입니다.

### ✔ TODO

구독 신청 페이지
- [x] 문구 변경
- [X] '서비스 출시 알림 신청하기' > '텔링미 소식 구독 신청하기' 로 수정
- [X] '서비스가 출시되면 가장 먼저 알려드릴게요!' > '텔링미의 새로운 이야기를 하나씩 풀어드릴게요!' 로 수정

회원가입 페이지
- [X] '네, 동의할게요' 누르면 자세히 창 꺼지게 변경
- [X] '네! 모두 동의할게요' 에서 '네!' 삭제
- [x] 서비스 이용 약관 페이지 체크박스 유지 시키기
- [X] 서비스 이용 약관 페이지의 disabled 버튼 커서 변경
- [x] disabled 버튼 아이콘 색상 변경하기

설정 페이지
- [X] 탈퇴 주의사항 수정
- [x] 탈퇴 주의사항 수정2
- [x] 탈퇴 주의사항에 슬픈 듀이 넣기
- [X] '푸시 알림 받기' 토글 키고 뒤로 갔다 들어오면 변경사항 반영 안됨 오류 있음
- [X] 설정 페이지 푸터 달기
- [X] 모바일 화면에서 화면 정보 수정 후, 메뉴로 넘어가버림 오류 있음
- [x] FAQ 추가
- [X] 헤더 고정 

기타
- [X] 툴팁 만들기
- [x] 툴팁 에러 수정
- [X] 푸터 통일
- [X] Info 아이콘 stroke, fill 수정

----- 계속 추가 할 예정 -----

### 🔴 ETC

기타 사항을 적어주세요.
예상 개발 기간 : 7일
