### ISSUE TITLE
1차 기능 수정하기

### ISSUE THREAD

**Issue by wisdomin121** [telling-me/tellingme-client#71]
### Description

1차 배포가 끝나고, 1차 기능 중 수정해야 할 것들이 생겼음

### ✔ TODO

- [x] 답변 작성 로직 변경
- [x] 회원가입 로직 변경
- [x] 카카오 로그인 로직 변경

+ 파이어베이스 코드 삭제

### 🔴 ETC

기타 사항을 적어주세요.
예상 개발 기간 : 3일
